### ISSUE TITLE
Frontend compilation failed

### ISSUE THREAD

**Issue by chenshih1** [UCLA-VAST/Merlin-UCLA#1]
Hello, I'm using Merlin with Vitis 2022.2 on ubuntu 20.04. The compilation seems to be successful, but I get an error while generating resource and performance estimates. The example code comes from [https://github.com/falconcomputing/merlin-compiler](https://github.com/Xilinx/merlin-compiler/issues/url)

root@cb252cec115b:~/merlinc-examples/Examples/dotproduct/build# make mcc_estimate
merlincc -c ../src/dot_product.cpp -D XILINX -o dot_product -funsafe-math-optimizations -I. -I --platform=vitis::/opt/xilinx/platforms/xilinx_u250_gen3x16_xdma_4_1_202210_1/xilinx_u250_gen3x16_xdma_4_1_202210_1.xpfm
Smartmatch is experimental at /root/merlin-compiler/trunk//mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1096] Host - 'cb252cec115b' with linux x86_64-linux-gnu-thread-multi
INFO: [MERCC-1097] User -
INFO: [MERCC-1098] Time - Sat Nov 11 13:22:13 UTC 2023
INFO: [MERCC-1099] Directory - /root/merlinc-examples/Examples/dotproduct/build

INFO: [MERCC-1041] Setting platform to /opt/xilinx/platforms/xilinx_u250_gen3x16_xdma_4_1_202210_1/xilinx_u250_gen3x16_xdma_4_1_202210_1.xpfm.
INFO: [MERCC-1042] Checking Xilinx v++ ...
INFO: [MERCC-1043] Found Xilinx v++ : /home/chens/Xilinx/Vitis/2022.2/bin/v++
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1033] Syntax checking...
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1034] Synthesizability checking...
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1035] Interface synthesis...

ERROR: [MERCC-3058] Frontend compilation failed, please see the details in merlin.logERROR: [MERCC-3044] Merlin compilation failed. See above for each details.
make: *** [../../common/mcc_common.mk:143: dot_product.mco] Error 1

the .log doesn;t contain any details, so what's the error exactly?

**Comment by S12P** [comment]
Hi,

Your error is from mcc_common.mk which is used in the makefile of your example (https://github.com/falconcomputing/merlin-compiler/blob/master/Examples/dotproduct/build/Makefile).

Did you try to run merlincc <options> dot_product.cpp, without this Makefile ?

**Comment by chenshih1** [comment]
@S12P Hi,
i've tried to compile without makefile, and it met another error

root@28411110b0a9:~/merlinc-examples/Examples/dotproduct/src# merlincc -c dot_product.cpp -o dotproduct --platform=vitis::/opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_5_202210_1/xilinx_u50_gen3x16_xdma_5_202210_1.xpfm 
Smartmatch is experimental at /root/merlin-compiler/trunk//mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1096] Host - '28411110b0a9' with linux x86_64-linux-gnu-thread-multi
INFO: [MERCC-1097] User - 
INFO: [MERCC-1098] Time - Mon Nov 13 06:41:56 UTC 2023
INFO: [MERCC-1099] Directory - /root/merlinc-examples/Examples/dotproduct/src

INFO: [MERCC-1041] Setting platform to /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_5_202210_1/xilinx_u50_gen3x16_xdma_5_202210_1.xpfm.
INFO: [MERCC-1042] Checking Xilinx v++ ...
INFO: [MERCC-1043] Found Xilinx v++ : /home/chens/Xilinx/Vitis/2022.2/bin/v++
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1033] Syntax checking...
In file included from <built-in>:362:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
dot_product.cpp.

ERROR: [MERCC-3056] Synthesizability check failed.
Hint: only c++03 is supported now.
ERROR: [MERCC-3044] Merlin compilation failed. See above for each details.

however, if i add the include of gcc-4.9.4 into CPATH, the error will change.
root@28411110b0a9:~/merlinc-examples/Examples/dotproduct/src# export CPATH=/usr/local/gcc-4.9.4/include:$CPATH
root@28411110b0a9:~/merlinc-examples/Examples/dotproduct/src# export CPATH=/usr/local/gcc-4.9.4/lib/gcc/x86_64-linux-gnu/4.9.4/include:$CPATH
root@28411110b0a9:~/merlinc-examples/Examples/dotproduct/src# merlincc -c dot_product.cpp -o dotproduct --platform=vitis::/opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_5_202210_1/xilinx_u50_gen3x16_xdma_5_202210_1.xpfm 
Smartmatch is experimental at /root/merlin-compiler/trunk//mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1096] Host - '28411110b0a9' with linux x86_64-linux-gnu-thread-multi
INFO: [MERCC-1097] User - 
INFO: [MERCC-1098] Time - Mon Nov 13 06:43:19 UTC 2023
INFO: [MERCC-1099] Directory - /root/merlinc-examples/Examples/dotproduct/src

INFO: [MERCC-1041] Setting platform to /opt/xilinx/platforms/xilinx_u50_gen3x16_xdma_5_202210_1/xilinx_u50_gen3x16_xdma_5_202210_1.xpfm.
INFO: [MERCC-1042] Checking Xilinx v++ ...
INFO: [MERCC-1043] Found Xilinx v++ : /home/chens/Xilinx/Vitis/2022.2/bin/v++
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1033] Syntax checking...
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1034] Synthesizability checking...
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.
Smartmatch is experimental at /root/merlin-compiler/trunk/mars-gen/scripts/lib/message.pm line 392.

INFO: [MERCC-1035] Interface synthesis...


ERROR: [MERCC-3058] Frontend compilation failed, please see the details in merlin.logERROR: [MERCC-3044] Merlin compilation failed. See above for each details.

**Comment by S12P** [comment]
Please run with the following include (which have to be modified to match your Vitis version and path)

merlincc -c inv_mass.cpp -D XILINX -o kernel_inv_mass -d11 --attribute burst_total_size_threshold=36700160 --attribute burst_single_size_threshold=36700160 -funsafe-math-optimizations  -p=/tools/xilinx/platforms/xilinx_u55c_gen3x16_xdma_3_202210_1/xilinx_u55c_gen3x16_xdma_3_202210_1.xpfm -I ./ -I   -I /tools/xilinx/Vitis_HLS/2021.1/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/include/ -I /tools/xilinx/Vitis_HLS/2021.1/include/  -I /opt/merlin/sources/merlin-compiler/trunk/source-opt/include/apint_include/
